### ISSUE TITLE
Problem with Send Msg to Individual Method

### ISSUE THREAD

**Issue by mvillena3** [jhm15217/worthreading#97]
I noticed that I was getting your Fwd: This Video MIGHT Stop Romney From Becoming President email resent to me several times. I checked the Heroku logs (shown below) and I noticed there was an error with a subscriber being added to a user when he already was a subscriber. Thus, an internal server error response would be sent to Mailgun which is why they are retrying to send the email several times to me.

I'm found the source of the issue to be the send message to individual method which is adding a subscriber regardless of whether or not the person already is a subscriber. I'm working on fixing it.

2012-08-20T20:33:36+00:00 app[web.1]: Sent mail to mvillena3@gatech.edu (238ms)
2012-08-20T20:33:36+00:00 app[web.1]: Completed 500 Internal Server Error in 470ms
2012-08-20T20:33:36+00:00 app[web.1]: 
2012-08-20T20:33:36+00:00 app[web.1]: : INSERT INTO "relationships" ("created_at", "subscribed_id", "subscriber_id", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"):
2012-08-20T20:33:36+00:00 app[web.1]: ActiveRecord::RecordNotUnique (PGError: ERROR:  duplicate key value violates unique constraint "index_relationships_on_subscribed_id_and_subscriber_id"
2012-08-20T20:33:36+00:00 app[web.1]: DETAIL:  Key (subscribed_id, subscriber_id)=(30, 26) already exists.
2012-08-20T20:33:36+00:00 app[web.1]:   app/models/user.rb:85:in `send_msg_to_individual'
2012-08-20T20:33:36+00:00 app[web.1]:   app/controllers/emails_controller.rb:49:in`create'
2012-08-20T20:33:36+00:00 app[web.1]:   app/models/user.rb:46:in `add_subscriber'

**Comment by mvillena3** [comment]
Forgot to note I fixed it.

**Comment by jhm15217** [comment]
Good catch!

On Monday, August 20, 2012, mvillena3 wrote:

> I noticed that I was getting your Fwd: This Video MIGHT Stop Romney From
> Becoming President email resent to me several times. I checked the Heroku
> logs (shown below) and I noticed there was an error with a subscriber being
> added to a user when he already was a subscriber. Thus, an internal server
> error response would be sent to Mailgun which is why they are retrying to
> send the email several times to me.
> 
> I'm found the source of the issue to be the send message to individual
> method which is adding a subscriber regardless of whether or not the person
> already is a subscriber. I'm working on fixing it.
> 
> 2012-08-20T20:33:36+00:00 app[web.1]: Sent mail to mvillena3@gatech.edu<javascript:_e({}, 'cvml', 'mvillena3@gatech.edu');>(238ms)
> 2012-08-20T20:33:36+00:00 app[web.1]: Completed 500 Internal Server Error
> in 470ms
> 2012-08-20T20:33:36+00:00 app[web.1]:
> 2012-08-20T20:33:36+00:00 app[web.1]: : INSERT INTO "relationships"
> ("created_at", "subscribed_id", "subscriber_id", "updated_at") VALUES ($1,
> $2, $3, $4) RETURNING "id"):
> 2012-08-20T20:33:36+00:00 app[web.1]: ActiveRecord::RecordNotUnique
> (PGError: ERROR: duplicate key value violates unique constraint
> "index_relationships_on_subscribed_id_and_subscriber_id"
> 2012-08-20T20:33:36+00:00 app[web.1]: DETAIL: Key (subscribed_id,
> subscriber_id)=(30, 26) already exists.
> 2012-08-20T20:33:36+00:00 app[web.1]: app/models/user.rb:85:in
> send_msg_to_individual'
> 2012-08-20T20:33:36+00:00 app[web.1]:
> app/controllers/emails_controller.rb:49:increate'
> 2012-08-20T20:33:36+00:00 app[web.1]: app/models/user.rb:46:in
> `add_subscriber'
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jhm15217/worthreading/issues/97.

## 

James H. Morris
http://www.cs.cmu.edu/~jhm
